CREATE TABLE IF NOT EXISTS `categoria_planta` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`nome` VARCHAR(255) NOT NULL,
	`tipoTerra` VARCHAR(255) NOT NULL,
    `temperaturaIdeal` FLOAT NOT NULL,
    `consumoAguaPorDia` FLOAT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
